#--------------------------------------------------------------------------------------------------#

#------------------------FRAMEWORK FOR SOILWAT SIMULATIONS: CREATING SIMULATION RUNS, EXECUTING SIMULATIONS, AND AGGREGATING OUTPUTS

#--------------------------------------------------------------------------------------------------#

#------CODE developed and written by
# - Daniel R Schlaepfer (dschlaep@uwyo.edu, drs): 2009-2014
# - Donovan Miller (dlm): 2012
# - Ryan Murphy (rjm): 2012-2014
#for contact and further information see also: sites.google.com/site/drschlaepfer

#The R code below was tested on R version 3.0.2

#------DISCLAIMER: This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

#------USER INPUT OPTIONS
#Folder hierarchy
#	SWSF consists of one main project folder (dir.prj)
#	the main project folder contains three sub-folders
#		- 'dir.sw.in': for the input data (with three sub-folders: SoilWat-run project, datafiles, and  treatments),
#		- 'dir.sw.runs': for the individual simulation SoilWat-runs (these can also be under a different parent directory defined by 'dir.runs', e.g., at a external hard disk with lots of space), and
#		- 'dir.out': for the aggregated output files

#SWSF abilities include four different 'actions'
#	= "create": puts information and files together for each simulation SoilWat run
#	= "execute": executes the SoilWat simulations
#	= "aggregate": calculates aggregated response variables from the SoilWat output
#	= "concatenate": takes all individual temporary output files (those generated by each call to do_OneSite), sorts and concatenates the information, and writes all into one .csv output file

#Input data for the SoilWat simulation runs can come from one of five sources ('source_input')
#	= "datafiles&treatments":	- if actions include "create", then
#									- 1. step: if flagged in variable 'do.ExternalInformation', then data from external sources is accessed prior to starting simulations runs for all runs at once, and written to the corresponding 'datafile.X' and the use-flag set appropriately (see step 4.). Options include
#												- 'calculate field capacity and wilting point based on soil texture' (data is written to 'datafile.soils'): calculate soil texture based on Cosby et al. 1984 for those soil layers for which the use flag of sand and clay is set; executed after eventual call to extract soil texture information
#												- 'extract soil data from CONUS-SOIL' (data is written to 'datafile.soils' and 'datafile.soillayers'): extracts soil depth, bulk density, sand and clay content, and sets soil layer depths according to the CONUS-SOIL database
#												- 'extract sky/climate data from Climate Atlas for the US by NOAA' (data is written to 'datafile.cloud'),
#												- 'extract climate change scenarios' (data is written to 'datafile.weathersetup'),
#												- 'extract topography and elevation' (elevation, aspect, and slope is written to 'datafile.SWRunInformation'),
#									- 2. step: code creates SoilWat-runs with copies of SoilWat input files from 'dir.sw.in'
#									- 3. step: if flagged in 'datafile.treatments', then entire SoilWat input files or substantial chunks are replaced with files from folder 'dir.sw.tr' 
#												Options for input files: sw, filesin, prodin, siteparamin, soilsin, weathersetupin, cloudin
#												Options for chunks:
#													- 'weather' (the entire folder for the weather data, i.e., cloudin and yearly files of daily weather, is copied)
#													- 'climate.temp' (monthly deltaTempC addands are loaded from table according to scenario name, which are the columns in table)
#													- 'climate.ppt' (monthly PPT scaling factors are loaded from table according to scenario name, which are the columns in table)
#													- 'ppt.shifted' & 'shiftedPPT.Category' (monthly PPT scaling factors are loaded from table according to scenario name, which are the columns in table, rows/sites are selected by 'shiftedPPT.Category')
#													- 'lookup transpiration regions for each soil layer based on a table' (data is written to 'datafile.soils'): region distribution type for each SoilWat-run is loaded from 'datafile.treatments';
#													- 'lookup evaporation coefficients for each soil layer based on a table' (data is written to 'datafile.soils'): coefficient distribution type for each SoilWat-run is loaded from 'datafile.treatments';
#													- 'lookup transpiration coefficients for each soil layer based on a table' (data is NOT written to 'datafile.soils'): coefficient distribution type for each SoilWat-run is loaded from 'datafile.treatments';
#													- 'lookup snow density based on a table' (data is written to 'datafile.cloud'): snow density category for each SoilWat-run is loaded from 'datafile.treatments';
#									- 4-. step: if flagged in variable 'do.ExternalInformation', then data from external sources is accessed during each simulations runs and added to the SoilWat-run. Options include
#												- 'extract gridded daily weather from Maurer et al. 2002' (entire 'dirname.sw.runs.weather' is replaced), [data = Daily 1/8-degree gridded meteorological data [1 Jan 1949 - 31 Dec 2010]; http://www.engr.scu.edu/~emaurer/gridded_obs/index_gridded_obs.html; Maurer, E.P., A.W. Wood, J.C. Adam, D.P. Lettenmaier, and B. Nijssen, 2002, A Long-Term Hydrologically-Based Data Set of Land Surface Fluxes and States for the Conterminous United States, J. Climate 15, 3237-3251.]
#									- 4. step: if flagged in 'datafile.X' (with X = input file name), then information is added per flagged element to SoilWat input files taken from .csv datafiles in 'dir.sw.dat'
#								- if actions does not include "create", then code assumes that all SoilWat-runs are pre-prepared in the directory 'dir.sw.runs' (5. source);
#								  i.e., code obtains the list of simulation runs from 'datafile.SWRunInformation' and executes and/or aggregates the runs
#	= "folders":	assumes that all SoilWat-runs are pre-prepared in the directory 'dir.sw.runs' (5. source); 'actions' == "create" is ignored
#					i.e., unlike above, code obtains the list of simulation runs from reading the folder content and executes and/or aggregates the runs (this mode doesn't rely on 'SWRunInformation' for SoilWat input);
#					except if Index_RunInformation != NULL, then selected 'SWRunInformation' columns are appended to aggregated output

#	'datafile.SWRunInformation': datafile describes the design of the simulation experiment with the following columns (these and additional columns can be appended to the aggregated output files if selected by Index_RunInformation:
#						this datafile is in all cases needed except if 'source_input' == "folders" & Index_RunInformation == NULL
#						each row represents one SoilWat simulation (multiplied by Scenario_No)
#						Mandatory columns for all simulations, if this datafile present:
#							- 'Label' (string) = name of the SoilWat-run
#							- 'Include_YN' (0/1) = whether (1) or not (0) the run is included in the simulations;
#							- 'Scenario_No' (integer) = number of climate scenarios in addition to the standard scenario (e.g., Scenario_No == 2, for scenarios current, B1, and A2)
#						Additional mandatory columns if 'source_input' == "datafiles&treatments":
#							- 'ScenarioX' (string) = name of scenario number X; NOTE: if extracting climate change information then these scenario names must correspond in alphabetical order to the folder names in dir.external/ExtractClimateScenarios
#						Additional mandatory columns if 'source_input' == "datafiles&treatments" & 'actions' == "create":
#							- 'X_WGS84' (double) = longitude in degrees (WGS84)
#							- 'Y_WGS84' (double) = latitude in degrees (WGS84)
#							- 'ELEV_m' (double) = elevation (m a.s.l.)
#						Optional:
#							- 'ASPECT' (double) = aspect (degrees)
#							- 'SLOPE' (double) = slope (degrees)
#							- other variables

#	'datafile.treatments': datafile describes the treatment design
#						- the first line ('UseInformationToCreateSoilWatRuns') specifies which treatments are to be included (flags) (1) or not (0)
#						- Options for input files: for each SoilWat-run, enter name of input file to be copied from 'dir.sw.in.tr' to the SoilWat-run folder
#							- sw, filesin, prodin, siteparamin, soilsin, weathersetupin, cloudin
#						- Options for information chunks:
#							- 'LookupWeatherFolder': enter name of weather folder to be copied from 'dir.sw.in.tr' to the SoilWat-run folder
#							- 'LookupClimateTempScenarios' and 'LookupClimatePPTScenarios': enter name of column of table in 'dir.sw.in.tr' that is to be written to the weathersetup input file of the SoilWat-run folder
#							- 'LookupShiftedPPTScenarios': enter name of column-group of table in 'dir.sw.in.tr' that is to be written (multiplied to existing factors) to the weathersetup input file of the SoilWat-run folder
#							- 'LookupShiftedPPTCategory': enter name of row of table in 'dir.sw.in.tr'
#							- 'LookupSnowDensityFromTable_Category': enter name of row in snow-density table
#							- 'LookupTranspRegionsFromTable_Type': enter name of row in transpiration-region table
#							- 'LookupTranspCoeffFromTable_Type'{Grass, Shrub, Tree}: enter name of column in transpiration coefficient table

#	'datafile.soillayers':	datafile describes the soil layer structure: soil depth and layers
#						this datafile is needed if 'source_input' == "datafiles&treatments"
#						Mandatory columns:
#							- 'Label' (string) = name of the SoilWat-run
#							- 'SoilDepth_cm' (double) = soil depth in cm
#							- 'depth_LX' (double) = lower depth (cm) of soil layer X (X <= 'SoilLayer_MaxNo')

#For most SoilWat input files there is a datafile with adjustable parameters:
#	the first line ('UseInformationToCreateSoilWatRuns') of each datafile specifies which information is to be added to the input files (flags) (1) or not (0)
#	the first column: 'Label' (string) = name of the SoilWat-run
#	currently available datafiles:
#		- 'datafile.cloud'
#		- 'datafile.prod'
#		- 'datafile.siteparam'
#		- 'datafile.soils'
#		- 'datafile.weathersetup'

#	'datafile.climatescenarios': datafile describes the monthly PPT-factors and Temp-addands for each climate scenario, including the standard scenario, defined by 'Scenario_No' and 'Scenario_X' in 'datafile.SWRunInformation' 
#	the first line of datafile specifies whether information is to be added to the input files (flags)
#	NOTE: there are three ways to incorporate climate scenarios
#			1. Use 'Scenario_No', i.e., > 0, then each row represents 1+Scenario_No SoilWat-runs, the standard and 'Scenario_No' climate scenarios, as defined in 'datafile.climatescenarios'
#			2. For 'Scenario_No' == 0, then each row represents one climate scenario, the one in the standard columns, i.e., ending in "sc00", of 'datafile.climatescenarios'
#			3. Use one or a combinations of the treatment options of (weather, climate.temp, climate.ppt) and set 'Scenario_No' == 0, then each row represents its own climate scenario

#Output options: two types of aggregated output files are generated: (i) overal aggregated response variables, (ii) separate files for daily mean and daily SD of selected response variables (for two or three aggregated soil layers)
#	filename.aggregatedResults: name of file for (i) output
#	output_aggregate_daily: select response variables for which (ii) is calculated



#------ADDING FUNCTIONALIY
#Adding new treatments
#	1. Add new column to 'datafile.treatments'
#	2. If this is to add a new input file then
#		- Add code to add the input file in the 3. step of the create section in the do_OneSite function
#	   If this is to import data from external resources then
#		- Add code to import data in the 1. step of the external data section before to the do_OneSite function

#Adding new parameters to an existing datafile:
#	1. Add new column to datafile (with first row = use flag and then the data)
#	2. Add code to add this new information to the input file in the 4. step of the create section in the do_OneSite function

#Adding a new datafile
#	1. Create a new datafile
#	2. Define its name at input section 'filenames of files that contain input data or treatment codes'
#	3. Add code to import datafile and its use flags in the preparation section 'import data'
#	4. Add code to add its new information to the input file in the 4. step of the create section in the do_OneSite function

#Adding aggregation response variables
#	1. If its a new response variable group, then add a new line to 'output_aggregates'
#	2. Update 'n_variables' (number of response variables) in the preparation section 'constants'
#	3. Add code to calculate response variables in the aggregate section of do_OneSite function
#	4. Update res, resultfiles.Aggregates.header, and nv accordingly

#Adding a daily response variable
#	1. Add variable name to option list for output_aggregate_daily
#	2. Add code to calculate response variable in the 'daily output' part of the aggregate section of do_OneSite function
#	3. Update scaler, agg.file, agg.analysis, and agg.agg accordingly				

#soilWat shared object data indexs are listed in output.

#--------------------------------------------------------------------------------------------------#
#--------------------------------------------------------------------------------------------------#
#---------------------------------------------SETUP------------------------------------------------#

#------Clean the working environment
rm(list=ls(all=TRUE))

#------Overall timing
t.overall <- Sys.time()
be.quiet <- FALSE
print.debug <- FALSE

#------Mode of framework
minVersionRsoilwat <- "0.27.5"
num_cores <- 10
parallel_backend <- "mpi" #"snow" or "multicore" or "mpi"
parallel_runs <- TRUE

#------Rmpi Jobs finish within Wall Time------#
MaxRunDurationTime <- 1.5 * 60 *60 #Set the time duration for this job [in seconds], i.e. Wall time. As time runs out Rmpi will not send more work. Effects Insert into database and ensembles.
MaxDoOneSiteTime <- (MaxRunDurationTime - 11*60) #This will stop new Rmpi jobs at 'x' seconds before MaxRunDuration expires.
MinTimeConcat <- 10 * 60 * 60 #This is the minimum time remaining after execution needed to begin concat
MaxConcatTime <- 35 * 60 #This will stop any new sql file concat job at 'x' seconds before MaxRunDuration expires.

#------Repository in case installation of additional R packages is required
url.Rrepos <- "http://cran.us.r-project.org"

#--------------------------------------------------------------------------------------------------#
#------------------------USER INPUT

#------Set paths to simulation framework folders
#parent folder of simulation project
dir.prj <- "~/Documents/drschlaepfer/2_Research/200907_UofWyoming_PostDoc/Projects_My/Product_PowellCenter/6_Projects_Year1/Prj01_Texture/1_PC_TempDry_Simulations_Prj01_r2mini"
dir.prj <- dir.runs <- getwd()
	
#parent folder containing external data
dir.external <- "/Users/drschlaep/Documents/drschlaepfer/2_Research/200907_UofWyoming_PostDoc/Projects_My/Software/SoilWat/SoilWat_SimulationFrameworks/SoilWat_DataSet_External"

#paths to sub-folder hierarchy
dir.in <- file.path(dir.prj, "1_Data_SWInput")	#path to input data of SoilWat-runs)
dir.sw.dat <- file.path(dir.in, "datafiles")	#folder with datafiles to add information to SoilWat input files
dir.sw.in <- file.path(dir.in, "swrun")	#folder with complete SoilWat run setup (without yearly weather files, cloudin is in 'Input' folder and not in weather-folder: needs to be moved appropiately)
dir.sw.in.tr <- file.path(dir.in, "treatments")	#folder with treatment input files according to treatment instructions
dir.sw.in.reg <- file.path(dir.in, "regeneration")	#folder with regeneration files, one for each species = run of 'dailyRegeneration_byTempSWPSnow'
dir.sw.runs <- file.path(dir.runs, "3_Runs")	#path to SoilWat-runs 
dir.out <- file.path(dir.prj, "4_Data_SWOutputAggregated")	#path to aggregated output


#------Define actions to be carried out by simulation framework
#actions are at least one of c("external", "create", "execute", "aggregate", "concatenate", "ensemble")
actions <- c("create", "execute", "aggregate", "concatenate", "ensemble")
#continues with unfinished part of simulation after abort if TRUE
continueAfterAbort <- TRUE
#stores for each SoilWat simulation a folder with inputs and outputs if TRUE
saveSoilWatInputOutput <- FALSE
#store data in big input files for experimental design x treatment design
makeInputForExperimentalDesign <- FALSE
#check completeness of SoilWat simulation directories and of temporary output aggregation files; create a list with missing directories and files
checkCompleteness <- FALSE

#------Define how aggregated output should be handled:
cleanDB <- FALSE #This will wipe all the Tables at the begining of a run. Becareful not to wipe your data.
deleteTmpSQLFiles <- TRUE
copyCurrentConditionsFromTempSQL <- TRUE
copyCurrentConditionsFromDatabase <- FALSE #Creates a copy of the main database containing the scenario==climate.ambient subset
ensembleCollectSize <- 500 #This value is the chunk size for reads of 'runID' from the database, i.e., chunk size = ensembleCollectSize * scenario_No. Yellowstone 500 seems to work. Balance between available memory, cores, read/write times, etc..

#------Define type of simulations and source of input data
#Daily weather data: must be one of database, Maurer2002, or WeatherFolder (in MasterInput.csv, treatmentDesign.csv, or experimentalDesign.csv)
GriddedDailyWeatherFromMaurer2002_NorthAmerica <- FALSE 
WeatherDataFromDatabase <- FALSE
dbWeatherDataFile <- "/media/ryan/Storage/WeatherData/dbWeatherData.db"

#indicate if actions contains "external" which external information (1/0) to obtain from dir.external, don't delete any labels; GIS extractions not supported on JANUS
do.ExtractExternalDatasets <- c(
		"ExtractGriddedDailyWeatherFromNCEPCFSR_Global", 0, #code not integrated yet
		
		#Mean monthly PPT, Tmin, Tmax conditions: if using NEX or GDO-DCP-UC-LLNL, climate condition names must be of the form SCENARIO.GCM with SCENARIO being used for ensembles; if using climatewizard, climate condition names must be equal to what is in the respective directories
		#CMIP3
		"ExtractClimateChangeScenarios_CMIP3_ClimateWizardEnsembles_Global", 0, #50-km resolution for mean of 2070-2099
		"ExtractClimateChangeScenarios_CMIP3_ClimateWizardEnsembles_USA", 0, #12-km resolution for mean change between 2070-2099 and 1971-2000
		"ExtractClimateChangeScenarios_CMIP3_BCSD_GDODCPUCLLNL_USA", 0,	#1/8-degree resolution
		"ExtractClimateChangeScenarios_CMIP3_BCSD_GDODCPUCLLNL_Global", 0,	#1/2-degree resolution
		#CMIP5
		"ExtractClimateChangeScenarios_CMIP5_BCSD_GDODCPUCLLNL_USA", 0,	#1/8-degree resolution
		"ExtractClimateChangeScenarios_CMIP5_BCSD_GDODCPUCLLNL_Global", 0,	#1/2-degree resolution
		"ExtractClimateChangeScenarios_CMIP5_BCSD_NEX_USA", 0,	#30-arcsec resolution; requires live internet access
		
		#Mean monthly wind, relative humidity, and 100% - sunshine 
		"ExtractSkyDataFromNCEPCFSR_Global", 0, #code not integrated yet
		"ExtractSkyDataFromNOAAClimateAtlas_USA", 0,
		
		#Soil texture and topography
		"ExtractElevation_NED_USA", 0,	#1-arcsec resolution, National Elevation Dataset (ned.usgs.gov), currently downloaded only for western US
		"ExtractElevation_HWSD_Global", 0, #30-arcsec resolution, Harmonized World Soil Database 
		"ExtractSoilDataFromCONUSSOILFromSTATSGO_USA", 0
)

do.PriorCalculations <- c(
		"EstimateConstantSoilTemperatureAtUpperAndLowerBoundaryAsMeanAnnualAirTemperature", 0,
		"EstimateInitialSoilTemperatureForEachSoilLayer", 0,
		"CalculateFieldCapacityANDWiltingPointFromSoilTexture", 0,
		"CalculateBareSoilEvaporationCoefficientsFromSoilTexture", 0
)

#------Time frame of simulation: if not specified in the treatment datafile
#year when SoilWat starts the simulation
simstartyr  <- 1979
#first year that is used for output aggregation, e.g., simstartyr + 1
getStartYear <- function(simstartyr){
	return(simstartyr + 1)
}
startyr <- getStartYear(simstartyr)
#year when SoilWat ends the simulation
endyr <- 2010

#------Meta-information of input data
datafile.windspeedAtHeightAboveGround <- 10 #SoilWat requires 2 m, but some datasets are at 10 m, e.g., NCEP/CRSF: this value checks windspeed height and if necessary converts to u2

#Climate conditions
climate.ambient <- "Current"	#Name of climatic conditions of the daily weather input when monthly climate perturbations are all off
#names of climate conditions/scenarios in the order of data in the climate scenarios datafile; this must have at least one entry (e.g., climate.ambient) and climate.ambient is forced to be the first entry
#if requesting ensembles, then names must include the scenario flags of 'ensemble.families'
#16 GCMs for CMIP3 (Maurer et al. 2007/2009)
climate.conditions <- c(climate.ambient, 	"sresa2.bccr_bcm2_0", "sresa2.cccma_cgcm3_1", "sresa2.cnrm_cm3", "sresa2.csiro_mk3_0", "sresa2.gfdl_cm2_0", "sresa2.gfdl_cm2_1", "sresa2.giss_model_e_r", "sresa2.inmcm3_0", "sresa2.ipsl_cm4", "sresa2.miroc3_2_medres", "sresa2.miub_echo_g", "sresa2.mpi_echam5", "sresa2.mri_cgcm2_3_2a", "sresa2.ncar_ccsm3_0", "sresa2.ncar_pcm1", "sresa2.ukmo_hadcm3",
											"sresb1.bccr_bcm2_0", "sresb1.cccma_cgcm3_1", "sresb1.cnrm_cm3", "sresb1.csiro_mk3_0", "sresb1.gfdl_cm2_0", "sresb1.gfdl_cm2_1", "sresb1.giss_model_e_r", "sresb1.inmcm3_0", "sresb1.ipsl_cm4", "sresb1.miroc3_2_medres", "sresb1.miub_echo_g", "sresb1.mpi_echam5", "sresb1.mri_cgcm2_3_2a", "sresb1.ncar_ccsm3_0", "sresb1.ncar_pcm1", "sresb1.ukmo_hadcm3")
#16 GCMs for CMIP5 by GDO-DCP-UC-LLNL (selection based on Knutti et al. 2013 GRL)
climate.conditions <- c(climate.ambient,	"RCP45.CanESM2", "RCP45.CESM1-CAM5", "RCP45.CSIRO-Mk3-6-0", "RCP45.EC-EARTH", "RCP45.FGOALS-g2", "RCP45.FGOALS-s2", "RCP45.GFDL-CM3", "RCP45.GISS-E2-R", "RCP45.HadGEM2-CC", "RCP45.HadGEM2-ES", "RCP45.inmcm4", "RCP45.IPSL-CM5A-MR", "RCP45.MIROC-ESM", "RCP45.MIROC5", "RCP45.MPI-ESM-MR", "RCP45.MRI-CGCM3",
											"RCP85.CanESM2", "RCP85.CESM1-CAM5", "RCP85.CSIRO-Mk3-6-0", "RCP85.EC-EARTH", "RCP85.FGOALS-g2", "RCP85.FGOALS-s2", "RCP85.GFDL-CM3", "RCP85.GISS-E2-R", "RCP85.HadGEM2-CC", "RCP85.HadGEM2-ES", "RCP85.inmcm4", "RCP85.IPSL-CM5A-MR", "RCP85.MIROC-ESM", "RCP85.MIROC5", "RCP85.MPI-ESM-MR", "RCP85.MRI-CGCM3")
#16 GCMs for CMIP5 by NEX (selection based on Knutti et al. 2013 GRL)
climate.conditions <- c(climate.ambient,	"RCP45.CanESM2", "RCP45.CESM1-CAM5", "RCP45.CNRM-CM5", "RCP45.CSIRO-Mk3-6-0", "RCP45.FGOALS-g2", "RCP45.FIO-ESM", "RCP45.GFDL-CM3", "RCP45.GISS-E2-R", "RCP45.HadGEM2-CC", "RCP45.HadGEM2-ES", "RCP45.inmcm4", "RCP45.IPSL-CM5A-MR", "RCP45.MIROC-ESM", "RCP45.MIROC5", "RCP45.MPI-ESM-MR", "RCP45.MRI-CGCM3",
											"RCP85.CanESM2", "RCP85.CESM1-CAM5", "RCP85.CNRM-CM5", "RCP85.CSIRO-Mk3-6-0", "RCP85.FGOALS-g2", "RCP85.FIO-ESM", "RCP85.GFDL-CM3", "RCP85.GISS-E2-R", "RCP85.HadGEM2-CC", "RCP85.HadGEM2-ES", "RCP85.inmcm4", "RCP85.IPSL-CM5A-MR", "RCP85.MIROC-ESM", "RCP85.MIROC5", "RCP85.MPI-ESM-MR", "RCP85.MRI-CGCM3")
#Future time period simulated = delta + simstartyr:endyr; also used to extract external climate conditions
deltaFutureToSimStart_yr <- 90

#Climate ensembles created across scenarios
ensemble.families <- c("SRESA2", "SRESA1B","SRESB1") # NULL or from c("SRESA2", "SRESA1B", "SRESB1"); this variable defines the groups for which ensembles of climate scenarios are calculated; corresponds to first part of scenario name
ensemble.families <- c("RCP45", "RCP85")
ensemble.levels <- c(2, 8, 15)  #if(!is.null(ensemble.families)) then this needs to have at least one value; this variable defines which ranked climate.conditions the ensembles are representing for each ensemble.families
save.scenario.ranks <- TRUE #if TRUE then for each ensemble.levels a file is saved with the scenario numbers corresponding to the ensemble.levels

#------Names of files that contain input data or treatment codes
datafile.SWRunInformation <- "SWRuns_InputMaster_TemperateArid_v11.csv"

datafile.soillayers <- "SWRuns_InputData_SoilLayers_WISE_withJacksonSoilDepth_v9.csv"	
datafile.soillayers <- "SWRuns_InputData_SoilLayers_WISE_ExtraTop5cm_withJacksonSoilDepth_v9.csv"	
datafile.soillayers <- "SWRuns_InputData_SoilLayers_DepthConstant100cm_v9.csv"	
datafile.treatments <- "SWRuns_InputData_TreatmentDesign_v14.csv"
datafile.Experimentals <- "SWRuns_InputData_ExperimentalDesign_v02.csv"

if ((any(actions == "external") || any(actions == "create") || any(actions == "execute") || any(actions == "aggregate")) ) {	#input datafiles in the folder ./datafiles
	datafile.climatescenarios <- "SWRuns_InputData_ClimateScenarios_Change_v11.csv"
	datafile.climatescenarios_values <- "SWRuns_InputData_ClimateScenarios_Values_SRESA2andSRESB1_v11.csv"
	datafile.cloud <- "SWRuns_InputData_cloud_v10.csv"
	datafile.prod <- "SWRuns_InputData_prod_v9.csv"
	datafile.siteparam <- "SWRuns_InputData_siteparam_v13.csv"
	datafile.soils <- "SWRuns_InputData_soils_WISE_withJacksonSoilDepth_v10.csv"
	datafile.soils <- "SWRuns_InputData_soils_WISE_ExtraTop5cm_withJacksonSoilDepth_v10.csv"
	datafile.soils <- "SWRuns_InputData_soils_FixedfromSoilsin_v10.csv"
	datafile.weathersetup <- "SWRuns_InputData_weathersetup_v10.csv"
}
if (( any(actions == "external") || any(actions == "create") || any(actions == "execute") || any(actions == "aggregate")) ) {	#input files in sub-folders ./treatments
	trfile.LookupClimatePPTScenarios <- "climate.ppt.csv"
	trfile.LookupClimateTempScenarios <- "climate.temp.csv"
	trfile.LookupShiftedPPTScenarios <- "shifted.ppt.csv"
	trfile.LookupEvapCoeffFromTable <- "BareSoilEvaporationCoefficientsPerSoilLayer.csv"
	trfile.LookupTranspCoeffFromTable <- "TranspirationCoefficients.csv"
	trfile.LookupTranspRegionsFromTable <- "TranspirationRegionsPerSoilLayer.csv"
	trfile.LookupSnowDensityFromTable <- "MeanMonthlySnowDensities_v2.csv"
	trfile.LookupVegetationComposition <- "VegetationComposition_MeanMonthly_v5.csv"
}

#------Northern/Southern Hemisphere adjustments
accountNSHemispheres_agg <- TRUE	#if TRUE and latitude < 0 (i.e., southern hemisphere) then the counting of timing variables is shifted by 6 months (e.g., July becomes 1st month, etc.)
accountNSHemispheres_veg <- TRUE 	#if TRUE and latitude < 0 (i.e., southern hemisphere) then shift monthly production values in prod.in file by six months

#------Output Header Columns------#
Index_RunInformation <- c(2:3, 5:11, 10, 16:17) #indices of columns of 'SWRunInformation', e.g, c(3, 7:9), or NULL, used for outputting SoilWat-run information in addition to create_treatments and climate scenario

#------Select aggregated output: time scale and variable groups
#simulation_timescales is at least one of c("daily", "weekly", "monthly", "yearly")
simulation_timescales <- c("daily", "monthly", "yearly")
#turn aggregation for variable groups on (1) or off (0), don't delete any variable group labels
output_aggregates <- c(
					#---Aggregation: SoilWat inputs
						"input_SoilProfile", 1,
            			"input_FractionVegetationComposition", 1,
						"input_VegetationBiomassMonthly", 1,
						"input_VegetationPeak", 1,
						"input_Phenology", 1,
						"input_TranspirationCoeff", 1,
						"input_ClimatePerturbations", 1,
					#---Aggregation: Climate and weather
						"yearlyTemp", 1,
						"yearlyPPT", 1,
						"dailySnowpack", 1,
						"dailyFrostInSnowfreePeriod", 1,
						"dailyPrecipitationEventSizeDistribution", 1,
						"yearlyAET", 1,
						"yearlyPET", 1,
						"monthlySeasonalityIndices", 1,
					#---Aggregation: Climatic dryness
						"yearlymonthlyTemperateDrylandIndices", 1,
						"yearlyDryWetPeriods", 1,
						"dailyWeatherGeneratorCharacteristics", 1,	#Takes about .5120 seconds for 33 scenarios is about 
						"dailyPrecipitationFreeEventDistribution", 1,
						"monthlySPEIEvents", 1,
					#---Aggregation: Climatic control
						"monthlyPlantGrowthControls", 1,
						"dailyC4_TempVar", 1,
						"dailyDegreeDays", 1,
					#---Aggregation: Yearly water balance
						"yearlyWaterBalanceFluxes", 1,
					#---Aggregation: Daily extreme values
						"dailyTranspirationExtremes", 1,
						"dailyTotalEvaporationExtremes", 1,
						"dailyDrainageExtremes", 1,
						"dailyInfiltrationExtremes", 1,
						"dailyAETExtremes", 1,
						"dailySWPextremes", 1,						#Takes about .7630 seconds for 33 scenarios is about .419 minutes
					#---Aggregation: Ecological dryness
						"dailyWetDegreeDays", 1,
						"monthlySWPdryness", 1,
						"dailySWPdrynessANDwetness", 1, 			#Takes about 3.200 seconds for 33 scenarios is about 1.76 minutes
						"dailySWPdrynessDurationDistribution", 1,	#Takes about .8132 seconds for 33 scenarios is about .447 minutes
						"dailySWPdrynessEventSizeDistribution", 1,	#Takes about .5120 seconds for 33 scenarios is about .2819334
						"dailySWPdrynessIntensity", 1,
					#---Aggregation: Mean monthly values
						"monthlyTemp", 1,
						"monthlyPPT", 1,
						"monthlySnowpack", 1,
						"monthlySoilTemp", 0,
						"monthlyRunoff", 1,
						"monthlyHydraulicRedistribution", 1,
						"monthlyInfiltration", 1,
						"monthlySWP", 1,
						"monthlyVWC", 1,
						"monthlySWC", 1,
						"monthlySWA", 0,
						"monthlyTranspiration", 1,
						"monthlySoilEvaporation", 1,
						"monthlyAET", 1,
						"monthlyPET", 1,
						"monthlyAETratios", 1,
						"monthlyPETratios", 1,
					#---Aggregation: Potential regeneration
						"dailyRegeneration_bySWPSnow", 0,
						"dailyRegeneration_GISSM", 0
)

#select variables to aggregate daily mean and SD, if "daily" is in simulation_timescales 

#options: NULL or at least one of c("AET", "Transpiration", "EvaporationSoil", "EvaporationSurface", "EvaporationTotal", "VWC", "SWC", "SWP", "Snowpack", "SWA", "Rain", "Snowfall", "Snowmelt", "SnowLoss", "Runoff", "Infiltration", "DeepDrainage", "PET", "TotalPrecipitation", "TemperatureMin", "TemperatureMax", "SoilTemperature")
output_aggregate_daily <- c("AET", "Transpiration", "EvaporationSoil", "EvaporationSurface", "EvaporationTotal", "VWC", "SWC", "SWP", "Snowpack", "SWA", "Rain", "Snowfall", "Snowmelt", "SnowLoss", "Runoff", "Infiltration", "DeepDrainage", "PET", "TotalPrecipitation", "TemperatureMin", "TemperatureMax")
#select variables to output as aggregated yearly time series
ouput_aggregated_ts <- NULL #c("Regeneration")


#------Parameters used in output aggregation
#critical soil water potential
SWPcrit_MPa <- c(-1.5, -3.0, -3.5, -3.9) #e.g., -1.5 or c(-3.0, -3.9, -4.9); critical soil water potential(s) to calculate 'dry' and 'wet' soils (aka wilting point) and available soil water

#degree-days
DegreeDayBase <- 0 # (degree C) base temperature above which degree-days are accumulated

#soil layers
Depth_TopLayers  <- 20 				#cm, distinguishes between top and bottom soil layer for overall data aggregation
AggLayer.daily <- TRUE				#if TRUE, then aggregate soil layers into 1-4 layers for mean/SD daily values; if FALSE, then use each soil layer
Depth_FirstAggLayer.daily  <- 10 	#cm, distinguishes between first and second soil layer for average daily data aggregation
Depth_SecondAggLayer.daily  <- 20 	#cm or NULL(=deepest soil layer), distinguishes between first and second soil layer for average daily data aggregation
Depth_ThirdAggLayer.daily  <- 60 	#cm, NULL(=deepest soil layer), or NA(=only two aggregation layers), distinguishes between second and third soil layer for average daily data aggregation
Depth_FourthAggLayer.daily  <- NULL	#cm, NULL(=deepest soil layer), or NA(=only three aggregation layers), distinguishes between third and fourth soil layer for average daily data aggregation

#regeneration: germination and establishment
season.start <- "LastSnow" # either doy or "LastSnow"
season.end <- "FirstSnow" # either doy or "FirstSnow"
germination.duration <- 7 # in days
germination.swp.surface <- -0.2 # in MPa, duration must have at least x MPa
establishment.duration <- 14 # in days
establishment.swp.surface <- -0.4 # in MPa, duration must have at least x MPa
establishment.delay <- 1 # start of establishment needs to occur latest x days after end of germination

#daily weather frequency distributions
bin.prcpSizes <- 5	#bins of x mm precipitation event sizes
bin.prcpfreeDurations <- 10	#bins of x consecutive days without precipitation

#coefficients: potential natural vegetation based on climate data (Jose Paruelo et al. 1996, 1998)
shrub.fraction.limit <- 0.2 	#page 1213: 0.2 in Paruelo JM, Lauenroth WK (1996) Relative abundance of plant functional types in grasslands and shrublands of North America. Ecological Applications, 6, 1212-1224.
growing.season.threshold.tempC <- 10 # based on Trewartha's D temperateness definition (with >=4 & < 8 months with > 10C)
growing.season.threshold.tempC <- 4 # based on standard input of mean monthly biomass values for vegetation composition


#------SoilWat files
sw <- "sw_v27"
sw.inputs <- "Input"	#must be string of length > 0; i.e. not compatible with SoilWat versions < 21
sw.outputs <- "Output"	#sw_v20+: "Output", earlier versions ""
swFilesIn <- "files_v27.in"

if(any(actions == "create") || any(actions == "execute") || any(actions == "aggregate") ) {
	#sw input file names
	swOutSetupIn <- "outsetup_v27.in"
	swcsetupin <- "swcsetup.in"
	soilsin <- "soils_v23.in"
	yearsin <- "years.in"
	estabin <- "estab.in"
	weatherin <- "weathsetup_v20.in"
	cloudin <- "cloud_v20.in"
	prodin <- "prod_v21.in"
	siteparamin <- "siteparam_v26.in"
	filebasename.WeatherDataYear <- "weath"

	#characteristics of sw input files
	soilsin.firstDataLine <- 18	# 18, if soilsin >= v23; 17, if soilsin < v23
}

if(any(actions == "aggregate")){
	#index Numbers
	sw_aet			<-1
	sw_deepdrain	<-2
	sw_estabs		<-3
	sw_evsoil		<-4
	sw_evapsurface	<-5
	sw_hd			<-6
	sw_inf_soil		<-7
	sw_interception	<-8
	sw_percolation	<-9
	sw_pet			<-10
	sw_precip		<-11
	sw_runoff		<-12
	sw_snow			<-13
	sw_soiltemp		<-14
	sw_surfaceWater	<-15
	sw_swp			<-16
	sw_swa			<-17
	sw_swc			<-18
	sw_temp			<-19
	sw_transp		<-20
	sw_vwc			<-21
	sw_wetdays		<-22
	sw_logfile		<-23
	sw_yr			<-1
	sw_mo			<-2
	sw_wk			<-3
	sw_dy			<-4
	#sw output file names
	aetdy <- "aet.dy"
	aetwk <- "aet.wk"
	aetmo <- "aet.mo"
	aetyr <- "aet.yr"
	deepdraindy <- "deep_drain.dy"
	deepdrainwk <- "deep_drain.wk"
	deepdrainmo <- "deep_drain.mo"
	deepdrainyr <- "deep_drain.yr"
	evapsurfacedy <- "evap_surface.dy"
	evapsurfacewk <- "evap_surface.wk"
	evapsurfacemo <- "evap_surface.mo"
	evapsurfaceyr <- "evap_surface.yr"
	evsoildy <- "evap_soil.dy"
	evsoilwk <- "evap_soil.wk"
	evsoilmo <- "evap_soil.mo"
	evsoilyr <- "evap_soil.yr"
	hddy <- "hydred.dy"
	hdwk <- "hydred.wk"
	hdmo <- "hydred.mo"
	hdyr <- "hydred.yr"
	inf_soildy <- "infiltration.dy"
	inf_soilwk <- "infiltration.wk"
	inf_soilmo <- "infiltration.mo"
	inf_soilyr <- "infiltration.yr"
	interceptiondy <- "interception.dy"
	interceptionwk <- "interception.wk"
	interceptionmo <- "interception.mo"
	interceptionyr <- "interception.yr"
	percolationdy <- "percolation.dy"
	percolationwk <- "percolation.wk"
	percolationmo <- "percolation.mo"
	percolationyr <- "percolation.yr"
	petdy <- "pet.dy"
	petwk <- "pet.wk"
	petmo <- "pet.mo"
	petyr <- "pet.yr"
	precipdy <- "precip.dy"
	precipwk <- "precip.wk"
	precipmo <- "precip.mo"
	precipyr <- "precip.yr"
	runoffdy <- "runoff.dy"
	runoffwk <-	"runoff.wk"
	runoffmo <- "runoff.mo"
	runoffyr <- "runoff.yr"
	snowdy <- "snowpack.dy"
	snowwk <- "snowpack.wk"
	snowmo <- "snowpack.mo"
	snowyr <- "snowpack.yr"
	swady <- "swa.dy"
	swawk <- "swa.wk"
	swamo <- "swa.mo"
	swayr <- "swa.yr"
	swcdy <- "swc.dy"
	swcwk <- "swc.wk"
	swcmo <- "swc.mo"
	swcyr <- "swc.yr"
	vwcdy <- "vwc.dy"
	vwcwk <- "vwc.wk"
	vwcmo <- "vwc.mo"
	vwcyr <- "vwc.yr"
	swpdy <- "sw_pot.dy"
	swpwk <- "sw_pot.wk"
	swpmo <- "sw_pot.mo"
	swpyr <- "sw_pot.yr"
	tempdy <- "temp.dy"
	tempwk <- "temp.wk"
	tempmo <- "temp.mo"
	tempyr <- "temp.yr"
	transpdy <- "transp.dy"
	transpwk <- "transp.wk"
	transpmo <- "transp.mo"
	transpyr <- "transp.yr"
	wetdaysdy <- "wetdays.dy"
	wetdayswk <- "wetdays.wk"
	wetdaysmo <- "wetdays.mo"
	wetdaysyr <- "wetdays.yr"
	soiltempdy <- "soil_temp.dy"
	soiltempwk <- "soil_temp.wk"
	soiltempmo <- "soil_temp.mo"
	soiltempyr <- "soil_temp.yr"
}

##############################################################################
########################Source of the code base###############################

source("2_SoilWatSimulationFramework_Part4of4_Code_v50.R", echo=FALSE, keep.source=FALSE)

