
init_intracker <- function() {
  temp <- c("load_inputs", "calc_size", "spatial_setup", "prj_todos", "rng_setup", "dbWork",
    "dbW_paths", "dbW_sources", "dbW_current", "dbW_scenarios", "soil_data", "elev_data",
    "climnorm_data", "req_soillayers", "calc_bsevap", "table_lookup")

  # NA, don't prepare/check
  # TRUE, has been prepared/checked successfully
  # FALSE, needs yet to be prepared/checked
  as.data.frame(matrix(FALSE, nrow = length(temp), ncol = 4, dimnames = list(temp,
    c("prepared", "prep_time", "checked", "check_time"))))
}


todo_intracker <- function(SFSW2_prj_meta, tracker, status) {
  x <- SFSW2_prj_meta[["input_status"]][tracker, status]

  !is.na(x) && identical(x, FALSE)
}


isdone_intracker <- function(SFSW2_prj_meta, tracker, status) {
  x <- SFSW2_prj_meta[["input_status"]][tracker, status]

  !is.na(x) && identical(x, TRUE)
}

#' Update input tracker status
#'
#' @param ist A data.frame representing an input tracker as generated by function
#'  \code{init_intracker}.
#' @param tracker A character string. One of the rownames of \code{ist}.
#' @param prepared A logical value or \code{NULL}. If not \code{NULL}, then the requested
#'  tracker will be updated with this value and its time stamp set.
#' @param checked A logical value or \code{NULL}. If not \code{NULL}, then the requested
#'  tracker will be updated with this value and its time stamp set.
#' @param clean_subsequent A logical value. If \code{TRUE} then trackers in rows greater
#'  than \code{tracker} will be reset to \code{FALSE}.
#'
#' @return The updated data.frame \code{ist}.
#' @export
update_intracker <- function(ist, tracker, prepared = NULL, checked = NULL,
  clean_subsequent = FALSE) {

  irow <- which(tracker == dimnames(ist)[[1]])
  if (length(irow) != 1)
    stop("'update_intracker': 'tracker' does not exist (uniquely).")

  # Upate status of requested tracker
  if (!is.null(prepared)) {
    ist[irow, "prepared"] <- prepared
    ist[irow, "prep_time"] <- Sys.time()
  }
  if (!is.null(checked)) {
    ist[irow, "checked"] <- checked
    ist[irow, "check_time"] <- Sys.time()
  }

  # Set subsequent trackers to FALSE
  if (clean_subsequent && irow < dim(ist)[1])
    ist[(irow + 1):dim(ist)[1], ] <- FALSE

  ist
}
